#ifndef REMINDMELIB_GLOBAL_H
#define REMINDMELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REMINDMELIB_LIBRARY)
#  define REMINDMELIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REMINDMELIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REMINDMELIB_GLOBAL_H
